project:
  type: website
  output-dir: docs

website:
  title: "STAT 310"
  navbar:
    left:
      - file: index.qmd
        text: Home
      - file: schedule.qmd
        text: "Schedule"
      
  sidebar:
    - title: "Schedule"
      style: "docked"
      contents:
        - schedule.qmd
        - weeks/week-01.qmd
        - weeks/week-02.qmd

format:
  html:
    theme: 
      - united
      - customs.scss
    toc: true

editor: visual

